name: download-from-orphan-branch
description: todo

inputs:
  branch:
    description: todo
    required: true
  path:
    description: todo
    required: false
    default: "./"

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        BRANCH: ${{ inputs.branch }}
        DOWNLOAD_PATH: ${{ inputs.path }}
      run: |
        mkdir -p "$DOWNLOAD_PATH"
        git fetch origin "$BRANCH"
        git --work-tree="$DOWNLOAD_PATH" checkout origin/"$BRANCH" -- .
