name: download-from-orphan-branch
description: todo

inputs:
  branch:
    description: todo
    required: true
  path:
    description: todo
    required: false
    default: ${{ github.workspace }}

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        BRANCH: ${{ inputs.branch }}
        DOWNLOAD_PATH: ${{ inputs.path }}
      run: |
        bash ./.github/scripts/download-from-orphan-branch.sh
