name: upload-to-orphan-branch
description: todo

inputs:
  branch:
    description: todo
    required: true
  path:
    description: todo
    required: true
  comitter-name:
    description: todo
    required: false
    default: "github-actions[bot]"
  comitter-email:
    description: todo
    required: false
    default: "41898282+github-actions[bot]@users.noreply.github.com"
  commit-message:
    description: todo
    required: false
    default: ""
  if-no-files-found:
    description: todo
    required: false
    default: "ignore"
  overwrite:
    description: todo
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        BRANCH: ${{ inputs.branch }}
        FILES_PATH: ${{ inputs.path }}
        COMMITTER_NAME: ${{ inputs.comitter-name }}
        COMMITTER_EMAIL: ${{ inputs.comitter-email }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        IF_NO_FILES_FOUND: ${{ inputs.if-no-files-found }}
        OVERWRITE: ${{ inputs.overwrite }}
      run: |
        shopt -s globstar
        declare -A files=()
        for file_path in $FILES_PATH; do
          if [[ "${file_path:0:1}" == "!" ]]; then
            for file in $(find ${file_path:1} -type f); do
              unset files["$file"]
            done
          else
            for file in $(find $file_path -type f); do
              files["$file"]=1
            done
          fi
        done
        case $IF_NO_FILES_FOUND in
          ignore)
            ;;
          error)
            if [ "${#files[@]}" -eq 0 ]; then
              echo "No files found" >&2
              exit 1
            fi
            ;;
          *)
            echo "Unknown if-no-files-found: $IF_NO_FILES_FOUND" >&2
            exit 1
            ;;
        esac
        git worktree remove -f .upload_orphan_worktree || true
        git worktree add --detach .upload_orphan_worktree
        (
          cd .upload_orphan_worktree
          git switch --orphan "$BRANCH"
          git reset --hard
          for file in "${!files[@]}"; do
            dir="$(dirname "$file")"
            mkdir -p "$dir"
            cp "../$file" "$dir"
            git add "$file"
          done
          git -c "user.name=$COMMITTER_NAME" \
            -c "user.email=$COMMITTER_EMAIL" \
            commit --allow-empty --allow-empty-message -m "$COMMIT_MESSAGE"
          git push $([ "$OVERWRITE" = true ] && echo -f) origin "HEAD:$BRANCH"
        )
        git worktree remove -f .upload_orphan_worktree
