name: upload-to-orphan-branch
description: todo

inputs:
  branch:
    description: todo
    required: true
  path:
    description: todo
    required: true
  comitter-name:
    description: todo
    required: false
    default: "github-actions[bot]"
  comitter-email:
    description: todo
    required: false
    default: "41898282+github-actions[bot]@users.noreply.github.com"
  commit-message:
    description: todo
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        BRANCH: ${{ inputs.branch }}
        FILES_PATH: ${{ inputs.path }}
        COMMITTER_NAME: ${{ inputs.comitter-name }}
        COMMITTER_EMAIL: ${{ inputs.comitter-email }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
      run: |
        git branch -D "$BRANCH" || true
        git worktree remove -f .upload_orphan_worktree || true
        git worktree add --detach .upload_orphan_worktree
        declare -A files=()
        for file_path in $FILES_PATH; do
          echo "Processing path: $file_path"
          if [[ "${file_path:0:1}" == "!" ]]; then
            for file in $(find ${file_path:1} -type f); do
              echo "Excluding file: $file"
              unset files["$file"]
            done
          else
            for file in $(find $file_path -type f); do
              echo "Including file: $file"
              files["$file"]=1
            done
          fi
        done
        (
          cd .upload_orphan_worktree
          git switch --orphan "$BRANCH"
          git reset --hard
          for file in "${!files[@]}"; do
            cp "../$file" .
            git add "$file"
          done
          git -c "user.name=$COMMITTER_NAME" \
            -c "user.email=$COMMITTER_EMAIL" \
            commit --allow-empty --allow-empty-message -m "$COMMIT_MESSAGE"
          git push -f origin "HEAD:$BRANCH"
        )
        git worktree remove -f .upload_orphan_worktree
