name: upload-to-orphan-branch
description: todo

inputs:
  branch:
    description: todo
    required: true
  path:
    description: todo
    required: true
  comitter-name:
    description: todo
    required: false
    default: "github-actions[bot]"
  comitter-email:
    description: todo
    required: false
    default: "41898282+github-actions[bot]@users.noreply.github.com"
  commit-message:
    description: todo
    required: false
    default: ""
  if-no-files-found:
    description: todo
    required: false
    default: "ignore"
  overwrite:
    description: todo
    required: false
    default: "false"
  include-hidden-files:
    description: todo
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        BRANCH: ${{ inputs.branch }}
        FILES_PATH: ${{ inputs.path }}
        COMMITTER_NAME: ${{ inputs.comitter-name }}
        COMMITTER_EMAIL: ${{ inputs.comitter-email }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        IF_NO_FILES_FOUND: ${{ inputs.if-no-files-found }}
        OVERWRITE: ${{ inputs.overwrite }}
        INCLUDE_HIDDEN_FILES: ${{ inputs.include-hidden-files }}
      run: |
        bash ./.github/scripts/upload-to-orphan-branch.sh
