name: examples

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  examples:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    env:
      BRANCH_PREFIX: _orphan_
      COMMITTER_NAME: github-actions[bot]
      COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      COMMIT_MESSAGE: examples

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - shell: bash
        run: |
          touch foo
          touch bar
          touch foobar

      - id: now
        shell: bash
        run: |
          echo "now=$(date +%s)" >> $GITHUB_OUTPUT

      - id: find-files
        shell: bash
        run: |
          files=$(find . -type f -name "*bar")
          {
            echo "files<<EOF"
            echo "$files"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - uses: ./.github/workflows/upload-to-orphan-branch
        with:
          branch: ${{ env.BRANCH_PREFIX }}${{ steps.now.outputs.now }}
          files: ${{ steps.find-files.outputs.files }}
          comitter-name: ${{ env.COMMITTER_NAME }}
          comitter-email: ${{ env.COMMITTER_EMAIL }}
          commit-message: ${{ env.COMMIT_MESSAGE }}

      - uses: ./.github/workflows/download-from-orphan-branch
        with:
          branch: _orphan_branch
          path: .download

      - shell: bash
        run: |
          ls .download
