name: examples

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  examples:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    env:
      BRANCH_PREFIX: _orphan_
      COMMITTER_NAME: github-actions[bot]
      COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      COMMIT_MESSAGE: examples
      MAX_AGE_SECONDS: 600

    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: make some files
        shell: bash
        run: |
          touch foo
          touch bar
          touch foobar

      - name: get now
        id: now
        shell: bash
        run: |
          echo "now=$(date +%s)" >> $GITHUB_OUTPUT

      - name: find files
        id: find-files
        shell: bash
        run: |
          files=$(find . -type f -name "*bar")
          {
            echo "files<<EOF"
            echo "$files"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: upload to orphan branch
        uses: ./.github/workflows/upload-to-orphan-branch
        with:
          branch: ${{ env.BRANCH_PREFIX }}${{ steps.now.outputs.now }}
          files: ${{ steps.find-files.outputs.files }}
          comitter-name: ${{ env.COMMITTER_NAME }}
          comitter-email: ${{ env.COMMITTER_EMAIL }}
          commit-message: ${{ env.COMMIT_MESSAGE }}

      - name: download from orphan branch
        uses: ./.github/workflows/download-from-orphan-branch
        with:
          branch: _orphan_branch
          path: .download

      - name: check downloaded files
        shell: bash
        run: |
          ls .download

      - name: delete old orphan branches
        shell: bash
        run: |
          now=$(date +%s)
          for branch in $(git branch -r --format="%(refname:lstrip=3)"); do
            if ! [[ "$branch" =~ "$BRANCH_PREFIX"* ]]; then continue; fi

            commit_count=$(git rev-list --count "origin/$branch")
            if [ "$commit_count" -ne 1 ]; then continue; fi

            committer_name=$(git log -1 --format=%an "origin/$branch")
            if [ "$committer_name" != "$COMMITTER_NAME" ]; then continue; fi

            committer_email=$(git log -1 --format=%ae "origin/$branch")
            if [ "$committer_email" != "$COMMITTER_EMAIL" ]; then continue; fi

            commit_message=$(git log -1 --format=%s "origin/$branch")
            if [ "$commit_message" != "$COMMIT_MESSAGE" ]; then continue; fi

            commit_date=$(git log -1 --format=%ct "origin/$branch")
            age=$((now - commit_date))
            if [ "$age" -lt "$MAX_AGE_SECONDS" ]; then continue; fi

            git push origin --delete "$branch"
          done
