name: examples

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  examples:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: make some files
        shell: bash
        run: |
          touch {foo,bar,foobar}
          mkdir -p dir
          touch dir/{foo,foobar}
          mkdir -p dir1/dir2/dir3/foobar
          touch dir1/dir2/dir3/foobar/{foo.txt,bar.md}
          mkdir -p .dir1/dir2
          touch .dir1/dir2/foo
          mkdir -p dir1/.dir2
          touch dir1/.dir2/foo
          touch dir1/dir2/.foo
          touch dir1/dir2/foo

      - name: get now
        id: now
        shell: bash
        run: |
          echo "now=$(date +%s)" >> $GITHUB_OUTPUT

      - name: upload to orphan branch
        uses: daiji256/upload-to-orphan-branch@v1
        with:
          branch: _orphan_${{ steps.now.outputs.now }}
          path: |
            *bar
            dir1/**/?oo[abc]ar/*.txt
            !foobar
            dir/
            .dir1/dir2/foo
            dir1/.dir2/foo
            dir1/dir2/.foo
            ./dir1/dir2/foo
            foo/foo/foo/

      - name: download from orphan branch
        uses: daiji256/download-from-orphan-branch@v1
        with:
          branch: _orphan_${{ steps.now.outputs.now }}
          path: .download

      - name: check downloaded files
        shell: bash
        run: |
          find .download -type f

      - name: delete old orphan branches
        uses: daiji256/delete-orphan-branch@v1
        with:
          branch-regex: _orphan_.*
          older-than-seconds: 600 # 10 minutes
